apiVersion: apps/v1
kind: Deployment
metadata:
  name: tactical-celery
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tactical-celery
  template:
    metadata:
      labels:
        app: tactical-celery
    spec:
      containers:
        - name: celery
          image: {{ .Values.image.backend }}
          command: ["/entrypoint.sh"]
          args: ["tactical-celery"]
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: tactical-backend-config
          env:
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/tactical
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tactical-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tactical-secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: redis
