apiVersion: v1
kind: Service
metadata:
  name: tactical-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tactical-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
