{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tactical-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.frontend }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tactical-frontend
                port:
                  number: 8080
    - host: {{ .Values.ingress.hosts.backend }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tactical-backend
                port:
                  number: 8080
    - host: {{ .Values.ingress.hosts.mesh }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meshcentral
                port:
                  number: 8080
{{- end }}
