apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      securityContext:
        {{- if .Values.podSecurityContext }}
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        {{- end }}
      containers:
        - name: nats
          image: "{{ .Values.image.nats }}:{{ .Values.image.tag | default "latest" }}"
          securityContext:
            {{- if .Values.securityContext }}
            {{- toYaml .Values.securityContext | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 4222
            - containerPort: 9235
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 50Mi
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 4222
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 2
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 4222
          #   initialDelaySeconds: 2
          #   periodSeconds: 5
          #   timeoutSeconds: 2
          #   failureThreshold: 3
