apiVersion: v1
kind: Service
metadata:
  name: tactical-nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: tactical-nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    app: tactical-nginx