apiVersion: apps/v1
kind: Deployment
metadata:
  name: tactical-nginx
  labels:
    app: tactical-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tactical-nginx
  template:
    metadata:
      labels:
        app: tactical-nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.nginx }}
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: certs
              mountPath: /opt/tactical/certs
          env:
            - name: API_HOST
              value: "api.tactical.local"
            - name: APP_HOST
              value: "frontend.tactical.local"
            - name: MESH_HOST
              value: "mesh.tactical.local"
      volumes:
        - name: certs
          emptyDir: {}