apiVersion: apps/v1
kind: Deployment
metadata:
  name: tacticalrmm-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tacticalrmm-backend
  template:
    metadata:
      labels:
        app: tacticalrmm-backend
    spec:
      initContainers:
        - name: tactical-init
          image: mmoroz612/tbe:1.1.1
          command: ["/entrypoint.sh", "tactical-init"]
          volumeMounts:
            - name: tactical-volume
              mountPath: /opt/tactical
          envFrom:
            - configMapRef:
                name: tacticalrmm-backend-config
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tacticalrmm-secrets
                  key: DJANGO_SECRET_KEY
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tacticalrmm-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: tacticalrmm-secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: redis
      containers:
        - name: backend
          image: {{ .Values.image.backend }}
          command: ["/entrypoint.sh"]
          args: ["tactical-backend"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: tacticalrmm-backend-config
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tacticalrmm-secrets
                  key: DJANGO_SECRET_KEY
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/tacticalrmm
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tacticalrmm-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tacticalrmm-secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: redis
      volumes:
        - name: tactical-volume
          emptyDir: {}