apiVersion: v1
kind: Service
metadata:
  name: tactical-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tacticalrmm-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
