apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshcentral
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meshcentral
  template:
    metadata:
      labels:
        app: meshcentral
    spec:
      containers:
        - name: meshcentral
          image: {{ .Values.image.meshcentral }}
          ports:
            - containerPort: 443
          volumeMounts:
            - name: meshcentral-data
              mountPath: /home/node/app/meshcentral-data
      volumes:
        - name: meshcentral-data
          emptyDir: {}
