apiVersion: v1
kind: Service
metadata:
  name: meshcentral
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: meshcentral
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
