apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
    - name: monitoring
      port: 8222
