apiVersion: apps/v1
kind: Deployment
metadata:
  name: tactical-nginx
  labels:
    app: tactical-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tactical-nginx
  template:
    metadata:
      labels:
        app: tactical-nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.nginx }}
          ports:
            - containerPort: 80
            - containerPort: 443
