namespace: tacticalrmm

image:
  backend: mmoroz612/tbe:1.1.1
  frontend: mmoroz612/tfe:1.1.1
  meshcentral: mmoroz612/tmesh:1.1.1
  # meshcentral: typhonragewind/meshcentral
  redis: redis:6
  postgres: postgres:13
  nats: mmoroz612/tnats:1.1.1
  # nats: nats:latest
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

ingress:
  enabled: true
  className: nginx
  hosts:
    frontend: frontend.tacticalrmm.local
    backend: api.tacticalrmm.local
    mesh: mesh.tacticalrmm.local

persistence:
  postgres:
    size: 5Gi
  meshcentral:
    enabled: false # You can toggle PVC later

config:
  allowedHosts: "localhost,127.0.0.1,.tacticalrmm.local"
  apiHost: "https://api.tacticalrmm.local"
  frontendUrl: "https://frontend.tacticalrmm.local"
  meshUrl: "https://mesh.tacticalrmm.local"
  redisHost: "tacticalrmm-redis"
  redisPort: "6379"
  natsHost: "tacticalrmm-nats"
  natsPort: "4222"
  dbName: "tacticalrmm"
  dbUser: "tactical"
  timezone: "UTC"
