name: Deploy Helm Chart to Minikube

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  STAGE: "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up minikube
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Display Kubernetes nodes (debug)
        run: kubectl get nodes

      - name: Create namespace (if needed)
        run: kubectl create namespace tactical || true

      - name: Generate secrets.yaml from template
        run: |
          mkdir -p tactical-helm/environments/${{ env.STAGE }}
          envsubst < tactical-helm/environments/${{ env.STAGE }}/secrets.yaml.template > tactical-helm/environments/${{ env.STAGE }}/secrets.yaml
        env:
          MONGO_ROOT_PASS: ${{ secrets.MONGO_ROOT_PASS }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          DJANGO_SEC: ${{ secrets.DJANGO_SEC }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASS: ${{ secrets.PG_PASS }}
          PG_DB: ${{ secrets.PG_DB }}

      - name: Deploy Helm chart
        run: |
          helm upgrade --install tactical ./tactical-helm \
            --namespace tactical \
            --create-namespace \
            --values ./tactical-helm/values.yaml \
            --values ./tactical-helm/environments/${{ env.STAGE }}/values.yaml \
            --values ./tactical-helm/environments/${{ env.STAGE }}/secrets.yaml \
            --set image.tag=1.1.1 \
            --wait --timeout 2m0s

      - name: Show deployed services
        run: kubectl get svc -n tactical
